### ISSUE TITLE
Deprecation / consolidation with `next-sitemap`

### ISSUE THREAD

**Issue by leerob** [SergeyMyssak/nextjs-sitemap#6]
Hello!

I see you mentioned you're looking for maintainers since you no longer have time to work on this. I totally understand 😄 

Would you consider deprecating/archiving this package in favor of https://github.com/iamvishnusankar/next-sitemap? I believe this would help the community consolidate efforts on a single package for sitemaps 🙏 If you don't want to, totally understand.

Thank you so much!

**Comment by SergeyMyssak** [comment]
Hello @leerob!

This is a good idea. But I will not archive this library, I will develop it further. I think it's cool when people have a choice among several libraries. There is some kind of struggle for quality :) 

I'll close this issue, but if you have any questions feel free to ask

**Comment by leerob** [comment]
Totally fine 😄
